local function make_block(x, y, z, id)
    commands.setblock(x, y, z, "computercraft:computer_command{ComputerId:" .. id .. "} destroy")
    commands.setblock(x, y + 1, z, "computercraft:wireless_modem_advanced[facing=down] destroy")
end
local x, y, z = commands.getBlockPosition()
y = y + 1
local cp_id = math.random(999, 9998)
commands.setblock(x, y, z, "computercraft:disk_drive{Item:{id:\"computercraft:computer_normal\",Count:1b,tag:{ComputerId:" .. cp_id .. "}}} destroy")
sleep(1)
local drive = peripheral.wrap("top")
if not drive or not drive.isDiskPresent() then error("Computer drive not generated or disk is not present", 2) end
local f = fs.open(fs.combine(drive.getMountPath(), "startup.lua"), "w")
f.write("shell.run(\"gps host\", commands.getBlockPosition())")
f.close()
make_block(x, y, z, cp_id)
make_block(x, y + 3, z, cp_id)
make_block(x, y, z + 4, cp_id)
make_block(x + 4, y, z, cp_id)
sleep(1)
commands.say(commands.computercraft("turn-on", "#" .. cp_id))
