name: Build and Publish

on:
  push:
    branches:
      - main  # Adjust this to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add repository, update and install craftos-pc
        run: |
          sudo add-apt-repository  -y ppa:jackmacwindows/ppa
          sudo apt update
          sudo apt -y install craftos-pc

      - name: Clone repository
        run: git clone https://github.com/Gobgob30/RanLuaStuff.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        run: |
          cd RanLuaStuff  # Change to your repository directory
          for folder in */; do
            if [ -f "$folder/init.lua" ]; then
              craft-os --mount-rw .="$folder" --mount-rw ./bin="../bin" --script "pastebin run 35C8TNCZ source:'$folder/init.lua' destination:'bin/$folder'" add_wget_and_pastebin_support:true rewrite:true allow_bad_compression_results:true
            fi
          done

      - name: Upload Release Assets
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/*
          asset_name: your-desired-asset-name.zip 
